spring:
  datasource:
    url: jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?sslmode=require
    hikari:
      data-source-properties:
        prepareThreshold: 0
    
    username: postgres.nsaoytpkiwfsnmlezbsa
    password: "Tanhung2602#"
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
mqtt:
  broker:
    url: tcp://broker.emqx.io:1883
  client:
    id: springboot_chicken_farm_backend
  topic: chuong_ga/users/+/sensors